on:
  workflow_dispatch:
  push:
    tags:
      - "*"

name: 📦 Continuous Deployment

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v6

      - name: 🐋 Setup Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd

      - name: 🔐 Login
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ⏳ Wait for Continuous Integration
        uses: lewagon/wait-on-check-action@78dd4dd5d9b337c14c3c81f79e53bf7d222435c1
        with:
          check-name: "ci"
          wait-interval: 10

          ref: ${{ github.ref }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: 🏗️ Build and Publish
        run: |
          docker buildx build -t banking-frontend:${{  github.ref_name }} -t banking-frontend:latest -f docker/Dockerfile --load .

          docker image tag banking-frontend ghcr.io/simplytest/banking-frontend
          docker push -a ghcr.io/simplytest/banking-frontend

      - name: 📦 Deploy
        uses: appleboy/ssh-action@55dabf81b49d4120609345970c91507e2d734799
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}

          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          script: |
            docker stop Banking-Frontend-Demo || true
            docker rm Banking-Frontend-Demo || true

            docker pull ghcr.io/simplytest/banking-frontend:latest
            docker run -d -p 4200:80 --rm --name=Banking-Frontend-Demo ghcr.io/simplytest/banking-frontend:latest

      - name: 🍃 Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: 🍃 Install pnpm
        uses: pnpm/action-setup@08c4be7e2e672a47d11bd04269e27e5f3e8529cb
        with:
          run_install: false

      - name: 🏗️ Install Dependencies
        run: |
          pnpm install

      - name: 💾 Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: 🌲 Install Cypress binary
        run: pnpm exec cypress install

      - name: 🧪 Smoke Tests
        run: |
          pnpm run test:smoketests

      - name: 🔍 Check for duplicate reports
        id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf
        with:
          skip_after_successful_duplicate: true
          concurrent_skipping: "same_content_newer"

      - name: 📋 Smoke Test Report
        uses: phoenix-actions/test-reporting@f957cd93fc2d848d556fa0d03c57bc79127b6b5e
        if: steps.skip_check.outputs.should_skip != 'true' && (success() || failure())
        with:
          name: 📋 Smoke Test Report
          reporter: java-junit
          path: "results/smoketests*.xml"

      # - name: 🧨 Detect Breaking Changes
      #   id: changes
      #   uses: simbo/changes-between-tags-action@v1
      #   with:
      #     tag-pattern: "^[a-zA-Z()]+!:"

      # - name: 🧯 Forward Breaking Changes
      #   if: contains(steps.changes.outputs.changes, '!')
      #   uses: benc-uk/workflow-dispatch@v1
      #   with:
      #     workflow: cd.yml
      #     repo: simplytest/banking-backend
